name: reserv
description: "A new Flutter project."
publish_to: "none"
version: 0.1.1

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.1.1
  firebase_messaging: ^15.0.2
  go_router: ^14.2.0
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  shared_preferences: ^2.2.3
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4
  dio: ^5.4.3+1
  table_calendar: ^3.1.2
  equatable: ^2.0.5
  flutter_spinkit: ^5.2.1
  smooth_page_indicator: ^1.2.0+3
  internet_connection_checker: ^1.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/svg/
    - assets/images/
